name: foodfinder
description: "A Resturant Food Order App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  toggle_switch: ^2.3.0
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_datepicker: ^29.2.11
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  flutter_easyloading: ^3.0.5
  get: ^4.7.2
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  geocoding: ^4.0.0
  # flutter_map: ^8.1.1 
  firebase_core: ^2.32.0
  firebase_auth: ^4.4.0
  latlong2: ^0.9.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_widget_from_html_core: ^0.16.0
  timeline_tile: ^2.0.0
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  flutter_facebook_auth: ^7.1.2 
  google_sign_in: ^6.3.0
  flutter_sslcommerz: ^2.5.1
  flutter_bkash: ^0.3.1
  flutter_paypal_payment: ^1.0.8
  flutter_stripe: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/applogo.png"
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 500